quarkus.http.port=8083

quarkus.datasource.db-kind=mysql
quarkus.datasource.username=teste
quarkus.datasource.password=testeteste
quarkus.datasource.reactive.url=mysql://localhost:3306/telemetry

quarkus.swagger-ui.path=swagger-ui
quarkus.swagger-ui.always-include=true

quarkus.container-image.build=true
quarkus.container-image.push=true

kafka.bootstrap.servers=localhost:9092

mp.messaging.outgoing.telemetry-data.connector=smallrye-kafka
mp.messaging.outgoing.telemetry-data.topic=Telemetry-Data
mp.messaging.outgoing.telemetry-data.value.serializer=org.apache.kafka.common.serialization.StringSerializer

# Asset-type-specific telemetry topics
mp.messaging.outgoing.telemetry-batteries.connector=smallrye-kafka
mp.messaging.outgoing.telemetry-batteries.topic=Telemetry-Batteries
mp.messaging.outgoing.telemetry-batteries.value.serializer=org.apache.kafka.common.serialization.StringSerializer

mp.messaging.outgoing.telemetry-solar.connector=smallrye-kafka
mp.messaging.outgoing.telemetry-solar.topic=Telemetry-Solar
mp.messaging.outgoing.telemetry-solar.value.serializer=org.apache.kafka.common.serialization.StringSerializer

mp.messaging.outgoing.telemetry-chargers.connector=smallrye-kafka
mp.messaging.outgoing.telemetry-chargers.topic=Telemetry-Chargers
mp.messaging.outgoing.telemetry-chargers.value.serializer=org.apache.kafka.common.serialization.StringSerializer
