# Database Configuration
quarkus.datasource.db-kind=mysql
quarkus.datasource.username=teste
quarkus.datasource.password=testeteste
quarkus.datasource.reactive.url=mysql://localhost:3306/gridbalancingrecommendation

# Schema Creation
myapp.schema.create=true

# Swagger UI
quarkus.swagger-ui.always-include=true
quarkus.swagger-ui.path=/swagger-ui

# Kafka Configuration
kafka.bootstrap.servers=localhost:9092
mp.messaging.outgoing.grid-balancing-recommendation.connector=smallrye-kafka
mp.messaging.outgoing.grid-balancing-recommendation.topic=GridBalancingRecomendation
mp.messaging.outgoing.grid-balancing-recommendation.value.serializer=org.apache.kafka.common.serialization.StringSerializer

# Recommendation threshold (e.g., 0.9 = 90% of max capacity)
gridbalancing.threshold.percent=0.9

# REST Client Configuration
quarkus.rest-client.telemetry-api.url=http://localhost:8081
quarkus.rest-client.utility-operator-api.url=http://localhost:8083
