# Database Configuration
quarkus.datasource.db-kind=mysql
quarkus.datasource.username=teste
quarkus.datasource.password=testeteste
quarkus.datasource.reactive.url=mysql://localhost:3306/energyanalytics

# Schema Creation
myapp.schema.create=true

# Swagger UI
quarkus.swagger-ui.always-include=true
quarkus.swagger-ui.path=/swagger-ui

# HTTP Configuration
quarkus.http.port=8087

# Kafka Configuration
kafka.bootstrap.servers=localhost:9092

# Kafka Outgoing Channels
mp.messaging.outgoing.energy-discharged-zone.connector=smallrye-kafka
mp.messaging.outgoing.energy-discharged-zone.topic=Energy-Discharged-Zone
mp.messaging.outgoing.energy-discharged-zone.value.serializer=org.apache.kafka.common.serialization.StringSerializer

mp.messaging.outgoing.energy-generated-prosumer.connector=smallrye-kafka
mp.messaging.outgoing.energy-generated-prosumer.topic=Energy-Generated-Prosumer
mp.messaging.outgoing.energy-generated-prosumer.value.serializer=org.apache.kafka.common.serialization.StringSerializer

mp.messaging.outgoing.energy-consumed-prosumer.connector=smallrye-kafka
mp.messaging.outgoing.energy-consumed-prosumer.topic=Energy-Consumed-Prosumer
mp.messaging.outgoing.energy-consumed-prosumer.value.serializer=org.apache.kafka.common.serialization.StringSerializer

mp.messaging.outgoing.average-soc.connector=smallrye-kafka
mp.messaging.outgoing.average-soc.topic=Average-SoC
mp.messaging.outgoing.average-soc.value.serializer=org.apache.kafka.common.serialization.StringSerializer
