quarkus.datasource.db-kind=mysql
quarkus.datasource.username=teste
quarkus.datasource.password=testeteste

quarkus.swagger-ui.path=swagger-ui
quarkus.swagger-ui.always-include=true	

quarkus.container-image.build=true
quarkus.container-image.push=true

# Kafka Configuration
kafka.bootstrap.servers=localhost:9092

# AssetLink Events
mp.messaging.outgoing.assetlink-created.connector=smallrye-kafka
mp.messaging.outgoing.assetlink-created.topic=AssetLink-Created
mp.messaging.outgoing.assetlink-created.value.serializer=org.apache.kafka.common.serialization.StringSerializer

mp.messaging.outgoing.assetlink-updated.connector=smallrye-kafka
mp.messaging.outgoing.assetlink-updated.topic=AssetLink-Updated
mp.messaging.outgoing.assetlink-updated.value.serializer=org.apache.kafka.common.serialization.StringSerializer

mp.messaging.outgoing.assetlink-deleted.connector=smallrye-kafka
mp.messaging.outgoing.assetlink-deleted.topic=AssetLink-Deleted
mp.messaging.outgoing.assetlink-deleted.value.serializer=org.apache.kafka.common.serialization.StringSerializer
