version: '3.8'

services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: gridbalancingrecommendation
      MYSQL_USER: teste
      MYSQL_PASSWORD: testeteste
    ports:
      - "3310:3306"
    volumes:
      - gridbalancingrecommendation-db:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - gridbalancingrecommendation-network

  gridbalancingrecommendation:
    build:
      context: .
      dockerfile: src/main/docker/Dockerfile.jvm
    ports:
      - "8085:8085"
    environment:
      QUARKUS_DATASOURCE_REACTIVE_URL: mysql://mysql:3306/gridbalancingrecommendation
      QUARKUS_DATASOURCE_USERNAME: teste
      QUARKUS_DATASOURCE_PASSWORD: testeteste
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - gridbalancingrecommendation-network
      - vpp-network

volumes:
  gridbalancingrecommendation-db:

networks:
  gridbalancingrecommendation-network:
    driver: bridge
  vpp-network:
    external: true
