quarkus.datasource.db-kind=mysql
quarkus.datasource.username=teste
quarkus.datasource.password=testeteste

quarkus.swagger-ui.path=swagger-ui
quarkus.swagger-ui.always-include=true

quarkus.container-image.build=true
quarkus.container-image.push=true

# Kafka Configuration
kafka.bootstrap.servers=localhost:9092
mp.messaging.outgoing.flexibility-offers.connector=smallrye-kafka
mp.messaging.outgoing.flexibility-offers.topic=Flexibility-Offers
mp.messaging.outgoing.flexibility-offers.value.serializer=org.apache.kafka.common.serialization.StringSerializer

# REST Client Configuration for Telemetry MS
quarkus.rest-client.telemetry-api.url=http://localhost:8081
quarkus.rest-client.telemetry-api.scope=jakarta.inject.Singleton
