# HTTP
quarkus.http.port=8084

quarkus.datasource.db-kind=mysql
quarkus.datasource.username=teste
quarkus.datasource.password=testeteste
quarkus.datasource.reactive.url=mysql://localhost:3306/flexibilityevent

quarkus.swagger-ui.path=swagger-ui
quarkus.swagger-ui.always-include=true

quarkus.container-image.build=true
quarkus.container-image.push=true

# Kafka Configuration
kafka.bootstrap.servers=localhost:29092,localhost:29093,localhost:29094

# Outgoing channel for flexibility offers
mp.messaging.outgoing.flexibility-offers.connector=smallrye-kafka
mp.messaging.outgoing.flexibility-offers.topic=Flexibility-Offers
mp.messaging.outgoing.flexibility-offers.value.serializer=org.apache.kafka.common.serialization.StringSerializer
