# HTTP

quarkus.datasource.db-kind=mysql
quarkus.datasource.username=teste
quarkus.datasource.password=testeteste

quarkus.swagger-ui.path=swagger-ui
quarkus.swagger-ui.always-include=true
quarkus.container-image.build=true
quarkus.container-image.push=true


quarkus.container-image.group=diogotrod
quarkus.datasource.reactive.url=mysql://ieproject202620260606160608141900000001.cmci0eu3ybvf.us-east-1.rds.amazonaws.com:3306/VPPaaS
